spring:
  application:
    name: auth-service
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/sample
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: sample
      password: password1!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    database: mysql
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql

server:
  port: 8081
